storage.filepath=src/main/resources/data.json
logging.level.ROOT=INFO
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=DEBUG

# ========== POSTGRES ==========
spring.datasource.url=jdbc:postgresql://localhost:5432/gym
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ========== JPA / HIBERNATE ==========
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html